version: "3"
services:
  write-db:
    image: postgres
    restart: always
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: Artem568011!
  read-db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_DATABASE="vf-read-db"
  event-store:
    image: mongo
    ports:
      - 27018:27017
    environment:
      - MONGO_DATABASE="vf-event-store"
    command: mongod --replSet vf-event-store-repl-set
    volumes:
      - ./scripts/event-store-mongoinit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro